# Site settings
title: luetkemj
subtitle: change is good
email: luetkemj@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  change is good
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://luetkemj.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Permalink
permalink: /:short_year:month:day/:title/
